### ISSUE TITLE
Error 404 when adding product to the cart

### ISSUE THREAD

**Issue by ozielguimaraes** [desenvolvedor-io/dev-store#12]
**Describe the bug**

**To Reproduce**
1. Go to 'home  page'
2. Select an product
3. Click on 'Add to cart'
5. See 404 error page

**Expected behavior**
When user click on `add to cart` the product should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/10086698/165348924-4e9ecbb7-ef8c-4a4e-bc38-cc8e272931f7.png)

**Comment by julianodev** [comment]
There is already an open issue-reporting this. #5

**Comment by EduardoPires** [comment]
Duplicated. Closing issue.
