### ISSUE TITLE
The mentioned code must be in english

### ISSUE THREAD

**Issue by wzuqui** [desenvolvedor-io/dev-store#13]
https://github.com/desenvolvedor-io/dev-store/blob/343c18ca46178c90b501f435dfe2dac2060c9eba/src/services/DevStore.Customers.API/Controllers/CustomerController.cs#L34

**Comment by EduardoPires** [comment]
Yes. All code must be in English. Some pieces of code were forgotten during the translation.

**Comment by jmoldyvan** [comment]
i got to the issue here, but i did see there was quite a bit more code not in english? let me know if you want some more help with going through the code for translations

**Comment by EduardoPires** [comment]
@jmoldyvan this was a project originally written in portuguese, but we decided to translate to english to be a global project. Some parts of code have been forgotten and need an english translation.

**Comment by EduardoPires** [comment]
Fixed in #17
