### ISSUE TITLE
Should be an english function name

### ISSUE THREAD

**Issue by thiaraujo** [desenvolvedor-io/dev-store#16]
https://github.com/desenvolvedor-io/dev-store/blob/44eed28c7178d37fe2fa6d62fb1eb8df36de9ec0/src/services/DevStore.Customers.API/Data/CustomerContext.cs#L55

**Comment by jmoldyvan** [comment]
just switching that to an english name? I got it

**Comment by jmoldyvan** [comment]
is that the only instance of the function name? or do i need to search through other files to translate?

**Comment by EduardoPires** [comment]
Fixed in #17
