### ISSUE TITLE
Wrong syntax in light compose file

### ISSUE THREAD

**Issue by HaraHeique** [desenvolvedor-io/dev-store#28]
There is a problem in **docker-compose-local-light.yml** compose file, that causes unable to run the app. As the image below shows the _ports_ is the main problem.

![image](https://user-images.githubusercontent.com/26990166/213842924-c2117e4b-2475-4c90-9665-17893fbaf0d1.png)

Just remove it and it will run perfectly.

**Comment by brunobritodev** [comment]
thx
