### ISSUE TITLE
Remove Dapper

### ISSUE THREAD

**Issue by brunohbrito** [desenvolvedor-io/dev-store#3]
There are some projects that are using Dapper. E.g [ProductRepository](https://github.com/desenvolvedor-io/dev-store/blob/c7fe42c3a05426d37ce47987641eda264e4a98d5/src/services/DevStore.Catalog.API/Data/Repository/ProductRepository.cs#L25). 

We are seeking to replace with EF Core. To be a database agnostic.

**Comment by EduardoPires** [comment]
Fixed in #8
